about_ui <- function(id) {
  ns <- shiny::NS(id)

  shinydashboard::tabItem(
    tabName = "about",
    shiny::h2("About"),

    shiny::h3("Funding"),
    shiny::tags$ul(
      shiny::tags$li(
        "This database and toolbox is funded by the Great Lakes Fishery Commission
      through grant number 2025_JOH_460024."
      )
    ), 
    shiny::h3("Contributors"),
    shiny::tags$ul(
      shiny::tags$li(
        "The following individuals provided thoughts, critiques, and design for this project with 
        the core group being: Timothy B. Johnson, James E. Breck, Steven R. Chipps, David Deslauriers, 
        Mark W. Kershner, Charles P. Madenjian, Brent W. Metcalfe, 
        Steven A. Pothoven, Michael D. Rennie, and Benjamin L. Hlina."
      ), 
      shiny::br(),
      shiny::tags$li(
        "The following individuals contributed to the database design and thoughts on 
        the programming of the toolbox: Benjamin L. Hlina, Michael H.P. O’Brien, and Jonathan D. Pye"
      ),
      shiny::br(),
      shiny::tags$li(
        "The following people have assisted in testing the database and toolbox: 
      Carolyn J. Foley, Kate M.J. Storey, Andrew Welbourne, and Mark J. Wuenschel"
      )
    ),
    shiny::h3("Code & Maintenance"),
    shiny::tags$ul(
      shiny::tags$li(
        "The database and toolbox are authored and maintained by Benjamin L. Hlina."
      ),
      shiny::br(),
      shiny::tags$li(
        "The source code is available on GitHub:",
        shiny::tags$a(
          href = "https://github.com/benjaminhlina/glatar-app",
          target = "_blank",
          
          shiny::icon("github"),
          "View Repository"
        )
      ),
      shiny::br(),
      shiny::tags$li(
        "This app has used LLMs as a tool to assist in development, however, 
      any code that has been generated by LLMs has been meticulously screened, 
      edited and redeveloped.
      
      If you would like to contribute to the code that generates the toolbox,
      please fork the repository, create a branch within your fork,
      implement your suggestions, and create a pull request on the main repository for
      the maintainer to review.

      This repository will not be accepting LLM submitted PRs nor PRs that contain directly copy 
      and pasted code from LLMs that has not be vetted and edited.
      Issues that are submitted by LLMs and/or copied and pasted from LLMs 
      will be deleted and ignored, as the issuer needs to have the ability 
      to be able to write their own issues."
      )
    ),

    shiny::h3("Citation"),
    shiny::tags$ul(
      shiny::tags$li(
        "If you use this toolbox in your research, please cite appropriately using the
        following: [INSERT CITATION]."
      )
    )
  )
}

about_server <- function(id) {
  shiny::moduleServer(id, function(input, output, session) {
    # future logic here
  })
}
