events {}

http {
  upstream shiny_backend {
    hash $remote_addr consistent;
    server shiny:3838;
  }

  server {
    listen 80;
    listen [::]:80;
    server_name glatar.org www.glatar.org gbif.glatar.org;

    location ^~ /.well-known/acme-challenge/ {
      root /var/www/certbot;
      default_type "text/plain";
      allow all;
    }

    location / {
      return 200 "Bootstrap Nginx Active";
    }
  }
}